### ISSUE TITLE
作者在吗？有些问题想请教一下你

### ISSUE THREAD

**Issue by xiaoluSF** [MobDeveloper163/GitBook_iOS_Notebook#1]
创建数字钱包最后你使用的那个框架，我使用TrustStore创建钱包的时候速度太慢了，要10多秒，web3swift那种keystore又不是我想要的格式，不想创建HD钱包，而是那种普通的钱包。
非常感谢。

**Comment by VVanaheim** [comment]
可以去优盾钱包的官网看看，代码开源，可以参考学习
